version: '3.3'
services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    entrypoint:
      [
        'docker-entrypoint.sh',
        '--default-authentication-plugin=mysql_native_password',
      ]
    environment:
      MYSQL_DATABASE: core_api_template
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=root --execute "SHOW DATABASES;"'
      interval: 10s
      timeout: 1s
      retries: 5
  core-api-template:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=v0.1.0
    image: core-api
    command: /bin/sh -c "sleep 30; /usr/core-api"
    volumes:
      - './certs/:/usr/certs/'
    ports:
      - '5000:5000'
    env_file:
      - .env
